import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geoflutterfire_plus/geoflutterfire_plus.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:tagme/features/rides/data/models/ride.dart';

part 'ride_repository.g.dart';

/// Repository handling Firestore CRUD for rides.
@riverpod
RideRepository rideRepository(Ref ref) {
  return RideRepository(firestore: FirebaseFirestore.instance);
}

class RideRepository {
  RideRepository({required FirebaseFirestore firestore})
      : _firestore = firestore;

  final FirebaseFirestore _firestore;

  CollectionReference<Map<String, dynamic>> get _ridesCollection =>
      _firestore.collection('rides');

  /// Creates a new ride document in Firestore.
  ///
  /// Writes origin/destination as nested maps with geopoint, geohash, and
  /// address for geo-query compatibility. Returns the auto-generated doc ID.
  Future<String> createRide(Ride ride) async {
    final data = ride.toJson();

    // Remove id (auto-generated by Firestore).
    data.remove('id');

    // Write timestamps.
    data['createdAt'] = FieldValue.serverTimestamp();
    data['updatedAt'] = FieldValue.serverTimestamp();

    // Write origin as nested geo map for geoflutterfire_plus queries.
    if (ride.originGeopoint != null) {
      data['origin'] = {
        ...GeoFirePoint(ride.originGeopoint!).data,
        'geohash': ride.originGeohash,
        'address': ride.originAddress,
      };
    } else {
      data['origin'] = {
        'geohash': ride.originGeohash,
        'address': ride.originAddress,
      };
    }

    // Write destination as nested geo map.
    if (ride.destinationGeopoint != null) {
      data['destination'] = {
        ...GeoFirePoint(ride.destinationGeopoint!).data,
        'geohash': ride.destinationGeohash,
        'address': ride.destinationAddress,
      };
    } else {
      data['destination'] = {
        'geohash': ride.destinationGeohash,
        'address': ride.destinationAddress,
      };
    }

    final docRef = await _ridesCollection.add(data);
    return docRef.id;
  }

  /// Reads a single ride by document ID.
  Future<Ride?> getRide(String id) async {
    final doc = await _ridesCollection.doc(id).get();
    if (!doc.exists || doc.data() == null) return null;
    return _rideFromDoc(doc);
  }

  /// Streams rides near a [userOrigin] within [radiusKm].
  ///
  /// Uses geoflutterfire_plus geo queries on the `origin` field.
  /// Filters for active or full rides only.
  Stream<List<Ride>> ridesNearOrigin(
    GeoPoint userOrigin, {
    double radiusKm = 1.0,
  }) {
    final center = GeoFirePoint(userOrigin);

    return GeoCollectionReference<Map<String, dynamic>>(_ridesCollection)
        .subscribeWithin(
          center: center,
          radiusInKm: radiusKm,
          field: 'origin',
          geopointFrom: (data) =>
              (data['origin'] as Map<String, dynamic>)['geopoint'] as GeoPoint,
        )
        .map((snapshots) {
      return snapshots
          .map(_rideFromDoc)
          .where((ride) => ride.status == 'active' || ride.status == 'full')
          .toList();
    });
  }

  /// Streams rides posted by [studentId], ordered by departure time descending.
  Stream<List<Ride>> myRides(String studentId) {
    return _ridesCollection
        .where('posterId', isEqualTo: studentId)
        .orderBy('departureTime', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs.map(_rideFromDoc).toList());
  }

  /// Updates a ride's status.
  Future<void> updateRideStatus(String rideId, String status) async {
    await _ridesCollection.doc(rideId).update({
      'status': status,
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  /// Cancels a ride by setting status to 'cancelled'.
  Future<void> cancelRide(String rideId) async {
    await updateRideStatus(rideId, 'cancelled');
  }

  /// Converts a Firestore document to a [Ride], handling nested geo fields.
  Ride _rideFromDoc(DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data()!;
    data['id'] = doc.id;

    // Extract origin GeoPoint from nested map.
    GeoPoint? originGeopoint;
    final originData = data['origin'] as Map<String, dynamic>?;
    if (originData != null) {
      originGeopoint = originData['geopoint'] as GeoPoint?;
      data['originGeohash'] = originData['geohash'] ?? data['originGeohash'];
      data['originAddress'] = originData['address'] ?? data['originAddress'];
    }

    // Extract destination GeoPoint from nested map.
    GeoPoint? destinationGeopoint;
    final destData = data['destination'] as Map<String, dynamic>?;
    if (destData != null) {
      destinationGeopoint = destData['geopoint'] as GeoPoint?;
      data['destinationGeohash'] =
          destData['geohash'] ?? data['destinationGeohash'];
      data['destinationAddress'] =
          destData['address'] ?? data['destinationAddress'];
    }

    // Convert Timestamps to DateTime for Freezed.
    if (data['departureTime'] is Timestamp) {
      data['departureTime'] =
          (data['departureTime'] as Timestamp).toDate().toIso8601String();
    }
    if (data['createdAt'] is Timestamp) {
      data['createdAt'] =
          (data['createdAt'] as Timestamp).toDate().toIso8601String();
    }

    // Remove nested maps that Freezed doesn't know about.
    data.remove('origin');
    data.remove('destination');
    data.remove('updatedAt');

    var ride = Ride.fromJson(data);
    ride = ride.copyWith(
      originGeopoint: originGeopoint,
      destinationGeopoint: destinationGeopoint,
    );
    return ride;
  }
}
