/// List of Bangladesh universities for the university picker.
const List<String> bdUniversities = [
  'AIUB',
  'BRACU',
  'NSU',
  'DU',
  'BUET',
  'IUB',
  'EWU',
  'CUET',
  'RUET',
  'KUET',
  'SUST',
  'JU',
  'RU',
  'CU',
  'UIU',
  'DIU',
  'AUST',
  'ULAB',
  'UAP',
  'Stamford',
  'East West University',
  'Green University',
  'Daffodil International University',
  'Leading University',
  'Primeasia University',
  'City University',
  'Southeast University',
  'Ahsanullah University of Science and Technology',
  'American International University-Bangladesh',
  'BRAC University',
  'North South University',
  'University of Dhaka',
  'Bangladesh University of Engineering and Technology',
  'Independent University, Bangladesh',
  'United International University',
  'University of Liberal Arts Bangladesh',
  'University of Asia Pacific',
];
